
import React, { useState } from 'react';
import { generatePrivacyPolicy } from '../services/geminiService';
import { UserProfile } from '../types';
import { jsPDF } from 'jspdf';

interface PolicyGeneratorProps {
  user: UserProfile;
  storeName: string;
  isPaid: boolean;
  onUpgrade?: () => void;
}

const PolicyGenerator: React.FC<PolicyGeneratorProps> = ({ user, storeName, isPaid, onUpgrade }) => {
  const [details, setDetails] = useState('');
  const [loading, setLoading] = useState(false);
  const [policy, setPolicy] = useState('');
  const [selectedType, setSelectedType] = useState('Privacy Policy');
  const [isExporting, setIsExporting] = useState(false);

  const types = [
    'Privacy Policy (CCPA/GDPR)',
    'Terms of Service',
    'Return & Refund Policy',
    'ADA Accessibility Statement'
  ];

  const handleGenerate = async () => {
    if (!details) return;
    setLoading(true);
    try {
      const result = await generatePrivacyPolicy(`Type: ${selectedType}. Store: ${storeName}. Context: ${details}`);
      setPolicy(result);
    } catch (error) {
      console.error(error);
      alert('Generation failed.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!isPaid || !policy) return;
    setIsExporting(true);
    
    try {
      const doc = new jsPDF();
      const timestamp = new Date().toLocaleDateString();
      const serial = `SS-PDF-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
      
      // Header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(16, 185, 129); // Emerald-600
      doc.text("SHOP SHIELDER", 20, 20);
      
      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139); // Slate-500
      doc.text("COMPLIANCE VAULT - VERIFIED FRAMEWORK", 20, 26);
      
      // Divider
      doc.setDrawColor(226, 232, 240); // Slate-200
      doc.line(20, 32, 190, 32);
      
      // Metadata
      doc.setFontSize(11);
      doc.setTextColor(15, 23, 42); // Slate-900
      doc.text(`Document Type: ${selectedType}`, 20, 42);
      doc.text(`Merchant: ${storeName} (${user.storeUrl})`, 20, 48);
      doc.text(`Verified Date: ${timestamp}`, 20, 54);
      doc.text(`Compliance Serial: ${serial}`, 20, 60);
      
      // Content
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85); // Slate-700
      const splitText = doc.splitTextToSize(policy, 170);
      doc.text(splitText, 20, 75);
      
      // Footer
      const pageCount = doc.getNumberOfPages();
      for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // Slate-400
        doc.text("This document is generated by Shop Shielder. Automated compliance framework v2.4.", 20, 285);
        doc.text(`Page ${i} of ${pageCount}`, 170, 285);
      }

      doc.save(`ShopShielder-${selectedType.replace(/\s+/g, '-')}-${storeName}.pdf`);
    } catch (err) {
      console.error("PDF Export failed", err);
      alert("PDF Export failed. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="bg-white rounded-[2.5rem] p-8 lg:p-10 border border-slate-200 shadow-sm relative overflow-hidden">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-2xl font-black tracking-tight uppercase italic">Policy Engine</h2>
          <div className="flex items-center space-x-2 bg-emerald-50 px-3 py-1.5 rounded-xl border border-emerald-100">
             <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></div>
             <span className="text-[9px] font-black uppercase tracking-widest text-emerald-700">Expert Review Live</span>
          </div>
        </div>
        <p className="text-slate-500 mb-8 text-sm font-medium leading-relaxed">Our hybrid model generates high-fidelity drafts which are then prepared for our compliance team's final validation.</p>
        
        <div className="space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {types.map(t => (
              <button 
                key={t}
                onClick={() => {
                  setSelectedType(t);
                  setPolicy('');
                }}
                className={`px-4 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest border transition-all ${selectedType === t ? 'bg-slate-900 text-white border-slate-900 shadow-lg' : 'bg-white text-slate-400 border-slate-200 hover:border-emerald-500 hover:text-emerald-600'}`}
              >
                {t}
              </button>
            ))}
          </div>

          <textarea
            className="w-full h-32 p-5 rounded-2xl bg-slate-50 border border-slate-200 focus:outline-none focus:border-emerald-500 text-sm font-medium"
            placeholder={`Context for ${selectedType}...`}
            value={details}
            onChange={(e) => setDetails(e.target.value)}
          />

          <button
            onClick={handleGenerate}
            disabled={loading || !details}
            className="w-full py-5 bg-emerald-600 text-white rounded-2xl font-black text-xs uppercase tracking-[0.2em] hover:bg-emerald-700 transition-all shadow-xl disabled:opacity-50"
          >
            {loading ? 'Orchestrating AI Draft...' : `Generate AI Draft`}
          </button>
        </div>
      </div>

      {policy && (
        <div className="bg-white rounded-[2.5rem] p-8 lg:p-10 border border-slate-200 shadow-xl relative overflow-hidden animate-in zoom-in duration-300">
          <div className="flex items-center justify-between mb-8">
            <h3 className="font-black text-slate-900 uppercase text-xs tracking-widest">Draft Preview: {selectedType}</h3>
            {isPaid && (
              <button 
                onClick={() => {
                  navigator.clipboard.writeText(policy);
                  alert('Text copied.');
                }}
                className="px-4 py-2 bg-emerald-50 text-emerald-600 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-emerald-100 transition-colors"
              >
                Copy Text
              </button>
            )}
          </div>

          <div className="relative group">
            <div className={`prose prose-sm max-w-none bg-slate-50 p-8 rounded-3xl border border-slate-100 h-[32rem] overflow-hidden font-mono text-[11px] whitespace-pre-wrap leading-loose transition-all duration-700 ${!isPaid ? 'blur-md select-none pointer-events-none opacity-40' : 'overflow-y-auto'}`}>
              {policy}
            </div>

            {!isPaid && (
              <div className="absolute inset-0 flex flex-col items-center justify-center p-8 text-center bg-white/10 backdrop-blur-[2px]">
                <div className="bg-white p-10 rounded-[3rem] shadow-2xl border border-slate-100 max-w-sm animate-in zoom-in">
                  <div className="w-16 h-16 bg-slate-900 text-white rounded-3xl flex items-center justify-center mx-auto mb-6 shadow-xl text-2xl">🔒</div>
                  <h4 className="text-xl font-black text-slate-900 uppercase italic mb-3 leading-none">Access Restricted</h4>
                  <p className="text-slate-500 text-xs font-medium mb-8 leading-relaxed">Activate your merchant shield to unlock full access and PDF exports.</p>
                  <button onClick={onUpgrade} className="w-full py-4 bg-emerald-600 text-white rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-emerald-700 shadow-xl transition-all">
                    Unlock Document
                  </button>
                </div>
              </div>
            )}
          </div>

          {isPaid && (
            <div className="mt-8 flex flex-col sm:flex-row justify-between items-center gap-6">
              <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest italic">Framework Integrity: v2.4 Certified</div>
              <button 
                onClick={handleDownloadPDF}
                disabled={isExporting}
                className="flex items-center space-x-2 px-8 py-4 bg-slate-900 text-white rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-emerald-600 shadow-lg transition-all"
              >
                {isExporting ? (
                  <div className="animate-spin rounded-full h-3 w-3 border-2 border-white/20 border-t-white"></div>
                ) : (
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" strokeLinecap="round" strokeLinejoin="round" strokeWidth="3"/></svg>
                )}
                <span>{isExporting ? 'Exporting...' : 'Download PDF'}</span>
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default PolicyGenerator;
